# AUTOINSTALLER
# Version: v0.2.0
# Author: 1172005thinh
## APPLICATION MODULE CONFIGURATION
### TARGET LIST
target=[
    # index,setup_file,install_script,install_flag,desktop_shortcut_flag
    0,"7z.exe","apps/7z/install.au3",true,true;
    1,"brave.exe","apps/Brave/install.au3",true,true;
    2,"discord.exe","apps/Discord/install.au3",true,true;
    3,"DockerDesktopInstaller.exe","apps/Docker/install.au3",true,true;
    4,"Fonts","apps/Fonts/install.au3",true,false;
    5,"git.exe","apps/Git/install.au3",true,true;
    6,"chrome-standalone.exe","apps/GoogleChrome/install.au3",true,true;
    7,"java.exe","apps/Java/install.au3",true,false;
    8,"kaspersky.exe","apps/Kaspersky/install.au3",true,true;
    9,"libreoffice.msi","apps/LibreOffice/install.au3",true,true;
    10,"office2024.exe","apps/MicrosoftOffice/install.au3",true,true;
    11,"mpc.exe","apps/MPC-HC/install.au3",true,true;
    12,"msys2.exe","apps/MSYS2/install.au3",true,true;
    13,"notepadpp.exe","apps/Notepad++/install.au3",true,true;
    14,"obs.exe","apps/OBS/install.au3",true,true;
    15,"potplayer.exe","apps/PotPlayer/install.au3",true,true;
    16,"python.exe","apps/Python/install.au3",true,true;
    17,"qbittorrent.exe","apps/qBittorrent/install.au3",true,true;
    18,"shell.msi","apps/Shell/install.au3",true,false;
    19,"tailscale.exe","apps/Tailscale/install.au3",true,true;
    20,"teamviewer.exe","apps/TeamViewer/install.au3",true,true;
    21,"ultraviewer.exe","apps/UltraViewer/install.au3",true,true;
    22,"unikey.exe","apps/Unikey/install.au3",true,true;
    23,"vcredist-AIO.exe","apps/VCRedist/install.au3",true,false;
    24,"vs_community.exe","apps/VisualStudio/install.au3",true,true;
    25,"vlc.exe","apps/VLC/install.au3",true,true;
    26,"vscode.exe","apps/VSCode/install.au3",true,true;
    27,"winrar.exe","apps/WinRAR/install.au3",true,true;
    28,"wireguard.exe","apps/WireGuard/install.au3",true,true;
    29,"yt-dlp.exe","apps/yt-dlp/install.au3",true,false;
    30,"zalo.exe","apps/Zalo/install.au3",true,true;
];
### CONFIGURATION
max_iteration=2;
log_path=C:/Auto-installer/install-apps.log;
clean_after_installing=true;
# END
